name: Publish
on:
  release:
    types:
      - released

jobs:

  # Prepare and publish the plugin
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version:  22
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependecies
        run: npm install
      - name: Build Plugin
        run: |
          npm run compile
          npm install @vscode/vsce
          vsce package
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./testit-management-${{ github.event.release.tag_name }}.vsix
